Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -28,30 +28,35 @@ jobs:
         run: dotnet build --no-restore
 
       - name: Ensure TestResults directory exists
-        run: mkdir -p ./TestResults
+        run: mkdir -p TestResults
 
       - name: Run tests
-        run: dotnet test --no-build --collect:"XPlat Code Coverage" --logger:"trx;LogFileName=test_results.trx" --results-directory ./TestResults || (echo "Test runner failed" && exit 1)
+        run: |
+          dotnet test --no-build --collect:"XPlat Code Coverage" --logger:"trx;LogFileName=test_results.trx" --results-directory TestResults
+          if [ $? -ne 0 ]; then
+            echo "Test runner failed"
+            exit 1
+          fi
 
       - name: Check if TestResults directory exists
-        run: if [ -d "./TestResults" ]; then echo "TestResults directory exists"; else echo "TestResults directory does not exist"; fi
+        run: if [ -d "TestResults" ]; then echo "TestResults directory exists"; else echo "TestResults directory does not exist"; fi
 
-      - name: List directory after tests
-        run: ls -R
+      - name: List TestResults directory
+        run: ls -R TestResults
 
       - name: Publish test results
         uses: actions/upload-artifact@v2
         with:
           name: test-results
-          path: '**/TestResults/*.trx'
+          path: TestResults/*.trx
 
       - name: Publish code coverage
         uses: codecov/codecov-action@v1
         with:
           token: ${{ secrets.CODECOV_TOKEN }}
-          files: ./TestResults/**/coverage.cobertura.xml
+          files: TestResults/coverage.cobertura.xml
           flags: unittests
           name: code-coverage
 
       - name: Display test results
-        run: cat ./TestResults/test_results.trx
+        run: cat TestResults/test_results.trx
